### ISSUE TITLE
Speeding Up Animations?

### ISSUE THREAD

**Issue by andrerfneves** [webtempest/meteor-animate#2]
What's the best way to time these transitions/animations? Should I force-edit the CSS classes of my respective animations or is there a way to implement that on the API of the package? Basically, my zoomIn and zoomOut transitions are just a tad too slow.

**Comment by mplatts** [comment]
Try adding another css class and changing the animation duration.. eg add the class 'zoom-slow' to whatever element has is being animated and add the following css:

```css
.zoom-slow {
  -webkit-animation-duration: 0.5s !important;
  animation-duration: 0.5s !important;
}
```
